sudo: required
services:
  - docker

before_install:
  - docker build -t tolunardahanli/docker-kubernates -f Dockerfile.dev .

script:
  - docker run -e CI=true tolunardahanli/docker-kubernates npm run test
  